data_airlines = [
    ["airline_name", "alias", "iso_country", "iata_code"],
    ["1Time Airline", "", "South Africa", "1T"],
    ["40-Mile Air", "", "United States", "Q5"],
    ["Ansett Australia", "", "Australia", "AN"],
    ["Abacus International", "", "Singapore", "1B"],
    ["Abelag Aviation", "", "Belgium", "W9"],
    ["Aigle Azur", "", "France", "ZI"],
    ["Aloha Airlines", "", "United States", "AQ"],
    ["American Airlines", "", "United States", "AA"],
    ["Asiana Airlines", "", "Republic of Korea", "OZ"],
    ["Askari Aviation", "", "Pakistan", "4K"],
    ["Afriqiyah Airways", "", "Libya", "8U"],
    ["Afrinat International Airlines", "", "Gambia", "Q9"],
    ["Allegiant Air", "", "United States", "G4"],
    ["Aban Air", "", "Iran", "K5"],
    ["ABSA - Aerolinhas Brasileiras", "", "Brazil", "M3"],
    ["Antrak Air", "", "Ghana", "04"],
    ["Airborne Express", "", "United States", "GB"],
    ["ABX Air", "", "United States", "GB"],
    ["Astral Aviation", "", "Kenya", "8V"],
    ["Aero Asia International", "", "Pakistan", "E4"],
    ["Air Togo", "", "Togo", "YT"],
    ["Advance Leasing Company", "", "United States", "4G"],
    ["Aztec Worldwide Airlines", "", "United States", "7A"],
    ["Air Tindi", "", "Canadian Territories", "8T"],
    ["Ada Air", "", "Albania", "ZY"],
    ["ADC Airlines", "", "Nigeria", "Z7"],
    ["Adria Airways", "", "Slovenia", "JP"],
    ["Air Europa", "", "Spain", "UX"],
    ["Aero Benin", "", "Benin", "EM"],
    ["Aegean Airlines", "", "Greece", "A3"],
    ["Air Atlantique", "", "United Kingdom", "KI"],
    ["Air Europe", "", "Italy", "PE"],
    ["Alaska Central Express", "", "United States", "KO"],
    ["Astraeus", "", "United Kingdom", "5W"],
    ["Aerosvit Airlines", "", "Ukraine", "VV"],
    ["Air Italy", "", "Italy", "I9"],
    ["American Falcon", "", "Argentina", "WK"],
    ["Alliance Airlines", "", "Australia", "QQ"],
    ["Ariana Afghan Airlines", "", "Afghanistan", "FG"],
    ["Aeroflot Russian Airlines", "", "Russia", "SU"],
    ["Air Bosna", "", "Bosnia and Herzegovina", "JA"],
    ["Air France", "", "France", "AF"],
    ["Air Caledonie International", "", "France", "SB"],
    ["Air Gabon", "", "Gabon", "GN"],
    ["Air Salone", "", "Sierra Leone", "2O"],
    ["Air Cargo Carriers", "", "United States", "2Q"],
    ["Air Senegal International", "", "Senegal", "V7"],
    ["Air Namibia", "", "Namibia", "SW"],
    ["Air Service Gabon", "", "Gabon", "G8"],
    ["Aerolitoral", "", "Mexico", "5D"],
    ["Amadeus Global Travel Distribution", "", "Spain", "1A"],
    ["Air Glaciers", "", "Switzerland", "7T"],
    ["Aeroper", "", "Peru", "PL"],
    ["Atlas Blue", "", "Morocco", "8A"],
    ["Air Alpha Greenland", "", "Denmark", "GD"],
    ["Air Hong Kong", "", "Hong Kong", "LD"],
    ["Aeromist-Kharkiv", "", "Ukraine", "HT"],
    ["Azerbaijan Airlines", "", "Azerbaijan", "J2"],
    ["Avies", "", "Estonia", "U3"],
    ["Airbus Industrie", "", "France", "AP"],
    ["Alpine Air Express", "", "United States", "5A"],
    ["Airblue", "", "Pakistan", "ED"],
    ["Air Berlin", "", "Germany", "AB"],
    ["Air Contractors", "", "Ireland", "AG"],
    ["Air India Limited", "", "India", "AI"],
    ["Air Bourbon", "", "Reunion", "ZB"],
    ["Air Atlanta Icelandic", "", "Iceland", "CC"],
    ["Air Srpska", "", "Bosnia and Herzegovina", "RB"],
    ["Air Tahiti Nui", "", "France", "TN"],
    ["Aero Services Executive", "", "France", "W4"],
    ["Arkia Israel Airlines", "", "Israel", "IZ"],
    ["Air Jamaica", "", "Jamaica", "JM"],
    ["Air One", "", "Italy", "AP"],
    ["Air Sahara", "", "India", "S2"],
    ["Air Malta", "", "Malta", "KM"],
    ["Amerijet International", "", "United States", "M6"],
    ["Air Japan", "", "Japan", "NQ"],
    ["Air Kiribati", "", "Kiribati", "4A"],
    ["Air Nippon Network Co. Ltd.", "", "Japan", "EH"],
    ["America West Airlines", "", "United States", "HP"],
    ["Air Wisconsin", "", "United States", "ZW"],
    ["Tatarstan Airlines", "", "Russia", "U9"],
    ["Air Libert", "", "France", "VD"],
    ["Air Lithuania", "", "Lithuania", "TT"],
    ["Air Malawi", "", "Malawi", "QM"],
    ["Air Sicilia", "", "Italy", "BM"],
    ["Air Macau", "", "Macao", "NX"],
    ["Air Midwest", "", "United States", "ZV"],
    ["Air Seychelles", "", "Seychelles", "HM"],
    ["AeroMéxico", "", "Mexico", "AM"],
    ["All Nippon Airways", "ANA All Nippon Airways", "Japan", "NH"],
    ["Air Nostrum", "", "Spain", "YW"],
    ["Air Niugini", "", "Papua New Guinea", "PX"],
    ["Air Arabia", "", "United Arab Emirates", "G9"],
    ["Air Canada", "", "Canada", "AC"],
    ["Air Baltic", "", "Latvia", "BT"],
    ["Air Nippon", "", "Japan", "EL"],
    ["Airnorth", "", "Australia", "TL"],
    ["Air North Charter - Canada", "", "Canada", "4N"],
    ["AOM French Airlines", "", "France", "IW"],
    ["Air New Zealand", "", "New Zealand", "NZ"],
    ["AVCOM", "", "Russia", "J6"],
    ["Aero VIP", "", "Argentina", "2D"],
    ["Air Vegas", "", "United States", "6V"],
    ["Alitalia Express", "", "Italy", "XM"],
    ["Asia Overnight Express", "", "Philippines", "OE"],
    ["Aero Flight", "", "Germany", "GV"],
    ["Arrow Air", "", "United States", "JW"],
    ["Arik Air", "", "Nigeria", "W3"],
    ["Aerocondor", "", "Portugal", "2B"],
    ["Aires", "", "S.A.", "4C"],
    ["Aerolineas Argentinas", "", "Argentina", "AR"],
    ["Air Armenia", "", "Armenia", "QN"],
    ["Alaska Airlines", "", "ALASKA", "AS"],
    ["Air Sinai", "", "Egypt", "4D"],
    ["Airstars", "", "Russia", "PL"],
    ["Atlantic Southeast Airlines", "", "United States", "EV"],
    ["Astrakhan Airlines", "", "Russia", "OB"],
    ["Air Tanzania", "", "Tanzania", "TC"],
    ["Air Burkina", "", "Burkina Faso", "2J"],
    ["Aero-Tropics Air Services", "", "Australia", "HC"],
    ["Airlines Of Tasmania", "", "Australia", "FO"],
    ["Air Saint Pierre", "", "France", "PJ"],
    ["Air Transport International", "", "United States", "8C"],
    ["Austrian Airlines", "", "Austria", "OS"],
    ["Augsburg Airways", "", "Germany", "IQ"],
    ["AirBridge Cargo", "", "Russia", "RU"],
    ["Abu Dhabi Amiri Flight", "", "United Arab Emirates", "MO"],
    ["Aeroflot-Nord", "", "Russia", "5N"],
    ["Aurigny Air Services", "", "United Kingdom", "GR"],
    ["Aus-Air", "", "Australia", "NO"],
    ["Austral Lineas Aereas", "", "Argentina", "AU"],
    ["Australian Airlines", "", "Australia", "AO"],
    ["Avianca - Aerovias Nacionales de Colombia", "", "AVIANCA", "AV"],
    ["Air Vanuatu", "", "Vanuatu", "NF"],
    ["Airlink Zambia", "", "Zambia", "K8"],
    ["Air Bangladesh", "", "Bangladesh", "B9"],
    ["Air Mediterranee", "", "France", "DR"],
    ["Aeroline GmbH", "", "Germany", "7E"],
    ["Air Wales", "", "United Kingdom", "6G"],
    ["Air Caraïbes", "", "France", "TX"],
    ["Air India Express", "", "India", "IX"],
    ["Asian Express Airlines", "", "Australia", "HJ"],
    ["Air Exel", "", "Netherlands", "XT"],
    ["AirAsia", "Air Asia", "Malaysia", "AK"],
    ["Axis Airways", "", "France", "6V"],
    ["Atlant-Soyuz Airlines", "", "Russia", "3G"],
    ["Alitalia", "", "Italy", "AZ"],
    ["Arcus-Air Logistic", "", "Germany", "ZE"],
    ["Amaszonas", "", "Bolivia", "Z8"],
    ["Air Zimbabwe", "", "Zimbabwe", "UM"],
    ["Aserca Airlines", "", "Venezuela", "R7"],
    ["Rossiya-Russian Airlines", "Pulkovo Aviation Enterprise", "Russia", "FV"],
    ["Aviaexpress", "", "Hungary", "RX"],
    ["American Eagle Airlines", "", "United States", "MQ"],
    ["Airshop", "", "Netherlands", "FF"],
    ["African Transport Trading and Investment Company", "", "Sudan", "ML"],
    ["Air Ivoire", "", "Ivory Coast", "VU"],
    ["Air Botswana", "", "Botswana", "BP"],
    ["Air Foyle", "", "United Kingdom", "GS"],
    ["Air Tahiti", "", "French Polynesia", "VT"],
    ["Air Urga", "", "Ukraine", "3N"],
    ["Air VIA", "", "Bulgaria", "VL"],
    ["Africa West", "", "Togo", "FK"],
    ["Avirex", "", "Gabon", "G2"],
    ["ATRAN Cargo Airlines", "", "Russian Federation", "V8"],
    ["Avensa", "", "Venezuela", "VE"],
    ["Avolar Aerolineas", "", "Mexico", "V5"],
    ["Air China", "", "China", "CA"],
    ["Aero Condor Peru", "", "Peru", "Q6"],
    ["Arctic Circle Air Service", "", "United States", "5F"],
    ["Air Corridor", "", "Mozambique", "QC"],
    ["Air Central", "", "Japan", "NV"],
    ["Air Chathams", "", "New Zealand", "CV"],
    ["Air Marshall Islands", "", "Marshall Islands", "CW"],
    ["Access Air", "", "United States", "ZA"],
    ["Air Algerie", "", "Algeria", "AH"],
    ["Adam Air", "", "Indonesia", "KI"],
    ["Astar Air Cargo", "", "United States", "ER"],
    ["Antinea Airlines", "", "Algeria", "HO"],
    ["Air Dolomiti", "", "Italy", "EN"],
    ["Aeroflot-Don", "", "Russia", "D9"],
    ["Air Madrid", "", "Spain", "NM"],
    ["Aero Airlines", "", "Estonia", "EE"],
    ["Air City", "", "Germany", "4F"],
    ["Aer Lingus", "", "Ireland", "EI"],
    ["Alpi Eagles", "", "Italy", "E8"],
    ["Air S", "", "Air S", "KY"],
    ["Air Fiji", "", "Fiji", "PC"],
    ["Air Finland", "", "Finland", "OF"],
    ["Air Pacific", "", "Fiji", "FJ"],
    ["Atlantic Airways", "", "Faroe Islands", "RC"],
    ["Air Florida", "", "United States", "QH"],
    ["Air Iceland", "", "Iceland", "NY"],
    ["Air Philippines", "", "Philippines", "2P"],
    ["Air Georgian", "", "Canada", "ZX"],
    ["Air Guinee Express", "", "Guinea", "2U"],
    ["Amber Air", "", "Lithuania", "0A"],
    ["Air Georgia", "", "Georgia", "DA"],
    ["Air Greenland", "", "Denmark", "GL"],
    ["Allegro", "", "Mexico", "LL"],
    ["Atlas Air", "", "United States", "5Y"],
    ["Air Guyane", "", "French Guiana", "GG"],
    ["Air D'Ayiti", "", "Haiti", "H9"],
    ["Air Comores International", "", "Comoros", "GG"],
    ["Air Horizon", "", "Togo", "8C"],
    ["Air Bagan", "", "Myanmar", "W9"],
    ["Atyrau Air Ways", "", "Kazakhstan", "IP"],
    ["Air Canada Jazz", "", "Canada", "QK"],
    ["Atlasjet", "", "Turkey", "KK"],
    ["Air Koryo", "", "Democratic People's Republic of Korea", "JS"],
    ["Air Astana", "", "Kazakhstan", "KC"],
    ["Albanian Airlines", "", "Albania", "LV"],
    ["Alidaunia", "", "Italy", "D4"],
    ["Alliance Air", "", "India", "CD"],
    ["Aerolane", "", "Ecuador", "XL"],
    ["Air Alps Aviation", "", "Austria", "A6"],
    ["Atlantis European Airways", "", "Armenia", "TD"],
    ["Air Luxor GB", "", "Guinea-Bissau", "L8"],
    ["Air Luxor", "", "Portugal", "LK"],
    ["Air Mauritius", "", "Mauritius", "MK"],
    ["Air Madagascar", "", "Madagascar", "MD"],
    ["Air Moldova", "", "Moldova", "9U"],
    ["Aero Mongolia", "", "Mongolia", "M0"],
    ["Air Plus Comet", "", "Spain", "A7"],
    ["Aeromexpress", "", "Mexico", "QO"],
    ["Air Mauritanie", "", "Mauritania", "MR"],
    ["Aeroland Airways", "", "Greece", "3S"],
    ["Astair", "", "Russian Federation", "8D"],
    ["Albarka Air", "", "Nigeria", "F4"],
    ["Aero Contractors", "", "Nigeria", "AJ"],
    ["Air Burundi", "", "Burundi", "8Y"],
    ["Aeropelican Air Services", "", "Australia", "OT"],
    ["Air Paradise International", "", "Indonesia", "AD"],
    ["Air Class Lineas Aereas", "", "Uruguay", "QD"],
    ["African Safari Airways", "", "Kenya", "QS"],
    ["Airbus France", "", "France", "4Y"],
    ["Air Mobility Command", "", "United States", "MC"],
    ["Aer Arann", "", "Ireland", "RE"],
    ["Air Austral", "", "France", "UU"],
    ["Asian Spirit", "", "Philippines", "6K"],
    ["Air Afrique", "", "Ivory Coast", "RK"],
    ["Airlinair", "", "France", "A5"],
    ["Aero Lanka", "", "Sri Lanka", "QL"],
    ["Armenian International Airways", "", "Armenia", "MV"],
    ["Air Salone", "", "Sierra Leone", "20"],
    ["Armavia", "", "Armenia", "U8"],
    ["Aeromar", "", "Dominican Republic", "BQ"],
    ["AeroRep", "", "Colombia", "P5"],
    ["Aero-Service", "", "Republic of the Congo", "BF"],
    ["Aerosur", "", "Bolivia", "5L"],
    ["Air Santo Domingo", "", "Dominican Republic", "EX"],
    ["Aero California", "", "Mexico", "JR"],
    ["Avient Aviation", "", "Zimbabwe", "Z3"],
    ["Air Service", "", "Macedonia", "M3"],
    ["Air Slovakia", "", "Slovakia", "GM"],
    ["Aircompany Yakutia", "", "Russia", "R3"],
    ["Aeromar", "", "Mexico", "VW"],
    ["Air Turks and Caicos", "", "Turks and Caicos Islands", "JY"],
    ["Arkefly", "", "Netherlands", "OR"],
    ["Airlines PNG", "", "Papua New Guinea", "CG"],
    ["Air Cal", "", "France", "TY"],
    ["AirTran Airways", "", "United States", "FL"],
    ["Air Transat", "", "Canada", "TS"],
    ["Avialeasing Aviation Company", "", "Uzbekistan", "EC"],
    ["Tyrolean Airways", "", "Austria", "VO"],
    ["Aero-Charter Ukraine", "", "Ukraine", "DW"],
    ["Air Ukraine", "", "Ukraine", "6U"],
    ["Aerolineas Galapagos (Aerogal)", "", "Ecuador", "2K"],
    ["Alrosa Mirny Air Enterprise", "", "Russia", "6R"],
    ["Baker Aviation", "", "United States", "8Q"],
    ["British Airways", "", "United Kingdom", "BA"],
    ["Biman Bangladesh Airlines", "", "Bangladesh", "BG"],
    ["Bluebird Cargo", "", "Iceland", "BF"],
    ["BACH Flugbetriebsges", "", "Austria", "B4"],
    ["Blue Dart Aviation", "", "India", "BZ"],
    ["B&H Airlines", "", "Bosnia and Herzegovina", "JA"],
    ["Buffalo Airways", "", "Canada", "J4"],
    ["Benin Golf Air", "", "Benin", "A8"],
    ["Belair Airlines", "", "Switzerland", "4T"],
    ["Bahamasair", "", "Bahamas", "UP"],
    ["Bringer Air Cargo Taxi Aereo", "", "Brazil", "E6"],
    ["Balkan Bulgarian Airlines", "", "", "LZ"],
    ["BA Connect", "", "United Kingdom", "TH"],
    ["British International Helicopters", "", "United Kingdom", "BS"],
    ["Bankair", "", "United States", "B4"],
    ["Bangkok Airways", "", "Thailand", "PG"],
    ["Blue1", "", "Finland", "KF"],
    ["Bearskin Lake Air Service", "", "Canada", "JV"],
    ["Bellview Airlines", "", "Nigeria", "B3"],
    ["bmi", "bmi British Midland", "United Kingdom", "BD"],
    ["bmibaby", "", "United Kingdom", "WW"],
    ["Bemidji Airlines", "", "United States", "CH"],
    ["Bismillah Airlines", "", "Bangladesh", "5Z"],
    ["Bouraq Indonesia Airlines", "", "Indonesia", "BO"],
    ["Blue Panorama Airlines", "", "Italy", "BV"],
    ["BRA-Transportes Aereos", "", "Brazil", "7R"],
    ["Bering Air", "", "United States", "8E"],
    ["Belavia Belarusian Airlines", "", "Belarus", "B2"],
    ["Bravo Air Congo", "", "Democratic Republic of the Congo", "K6"],
    ["Braniff International Airways", "", "United States", "BN"],
    ["Big Sky Airlines", "", "United States", "GQ"],
    ["BAL Bashkirian Airlines", "", "Russia", "V9"],
    ["Metro Batavia", "", "Indonesia", "7P"],
    ["Berjaya Air", "", "Malaysia", "J8"],
    ["Blue Wings", "", "Germany", "QW"],
    ["BAX Global", "", "", "8W"],
    ["Bayu Indonesia Air", "", "Indonesia", "BM"],
    ["Brit Air", "", "France", "DB"],
    ["Boston-Maine Airways", "", "United States", "E9"],
    ["Brussels Airlines", "SN Brussels Airlines", "Belgium", "SN"],
    ["Binter Canarias", "", "Spain", "NT"],
    ["Blue Air", "", "Romania", "0B"],
    ["British Mediterranean Airways", "", "United Kingdom", "KJ"],
    ["Bulgaria Air", "", "Bulgaria", "FB"],
    ["Barents AirLink", "", "Sweden", "8N"],
    ["CAL Cargo Air Lines", "", "Israel", "5C"],
    ["CHC Airways", "", "Netherlands", "AW"],
    ["Calima Aviacion", "", "Spain", "XG"],
    ["Calm Air", "", "Canada", "MO"],
    ["Camai Air", "", "United States", "R9"],
    ["Cameroon Airlines", "", "Cameroon", "UY"],
    ["CanJet", "", "Canada", "C6"],
    ["Canadian Airlines", "", "Canada", "CP"],
    ["Canadian North", "", "Canada", "5T"],
    ["Canadian Western Airlines", "", "Canada", "W2"],
    ["Cape Air", "", "United States", "9K"],
    ["Capital Cargo International Airlines", "", "United States", "PT"],
    ["Cargo 360", "", "United States", "GG"],
    ["Cargoitalia", "", "Italy", "2G"],
    ["Cargojet Airways", "", "Canada", "W8"],
    ["Cargolux", "", "Luxembourg", "CV"],
    ["Caribbean Airlines", "", "Trinidad and Tobago", "BW"],
    ["Caribbean Star Airlines", "", "Antigua and Barbuda", "8B"],
    ["Carpatair", "", "Romania", "V3"],
    ["Caspian Airlines", "", "Iran", "RV"],
    ["Cathay Pacific", "", "Hong Kong SAR of China", "CX"],
    ["Cayman Airways", "", "Cayman Islands", "KX"],
    ["Cebu Pacific", "", "Philippines", "5J"],
    ["Centavia", "", "Serbia", "7N"],
    ["Centralwings", "", "Poland", "C0"],
    ["Centre-Avia", "", "Russia", "J7"],
    ["Centurion Air Cargo", "", "United States", "WE"],
    ["Chalk's Ocean Airways", "", "United States", "OP"],
    ["Champion Air", "", "United States", "MG"],
    ["Changan Airlines", "", "China", "2Z"],
    ["Chari Aviation Services", "", "Chad", "S8"],
    ["Chautauqua Airlines", "", "United States", "RP"],
    ["Chicago Express", "", "United States", "C8"],
    ["China Airlines", "", "Taiwan", "CI"],
    ["China Cargo Airlines", "", "China", "CK"],
    ["China Eastern Airlines", "", "China", "MU"],
    ["China Northern Airlines", "", "China", "CJ"],
    ["China Northwest Airlines", "", "China", "WH"],
    ["China Postal Airlines", "", "China", "8Y"],
    ["China Southern Airlines", "", "China", "CZ"],
    ["China United Airlines", "", "China", "HR"],
    ["China Xinhua Airlines", "", "China", "XO"],
    ["Yunnan Airlines", "", "China", "3Q"],
    ["Chitaavia", "", "Russia", "X7"],
    ["Cielos Airlines", "", "Peru", "A2"],
    ["Cimber Air", "", "Denmark", "QI"],
    ["Cirrus Airlines", "", "Germany", "C9"],
    ["City Airline", "", "Sweden", "CF"],
    ["City Connexion Airlines", "", "Burundi", "G3"],
    ["CityJet", "", "Ireland", "WX"],
    ["BA CityFlyer", "", "United Kingdom", "CJ"],
    ["Civil Air Transport", "", "Taiwan", "CT"],
    ["Club Air", "", "Italy", "6P"],
    ["Coast Air", "", "Norway", "BX"],
    ["Coastal Air", "", "United States", "DQ"],
    ["Colgan Air", "", "United States", "9L"],
    ["Comair", "", "United States", "OH"],
    ["Comair", "", "South Africa", "MN"],
    ["CommutAir", "", "United States", "C5"],
    ["Comores Airlines", "", "Comoros", "KR"],
    ["Compania Mexicargo", "", "Mexico", "GJ"],
    ["Compass Airlines", "", "United States", "CP"],
    ["Condor Flugdienst", "", "Germany", "DE"],
    ["Consorcio Aviaxsa", "", "Mexico", "6A"],
    ["Contact Air", "Contactair", "Germany", "C3"],
    ["Continental Airlines", "", "United States", "CO"],
    ["Continental Airways", "", "Russia", "PC"],
    ["Continental Express", "", "United States", "CO"],
    ["Continental Micronesia", "", "United States", "CS"],
    ["Conviasa", "", "Venezuela", "V0"],
    ["Copa Airlines", "", "Panama", "CM"],
    ["Corsairfly", "", "France", "SS"],
    ["Corse-Mediterranee", "", "France", "XK"],
    ["Cosmic Air", "", "Nepal", "F5"],
    ["Croatia Airlines", "", "Croatia", "OU"],
    ["Crossair Europe", "", "Switzerland", "QE"],
    ["Cubana de Aviación", "", "Cuba", "CU"],
    ["Cyprus Airways", "", "Cyprus", "CY"],
    ["Cyprus Turkish Airlines", "", "Turkey", "YK"],
    ["Czech Airlines", "CSA Czech Airlines", "Czech Republic", "OK"],
    ["DAS Air Cargo", "", "Uganda", "WD"],
    ["DAT Danish Air Transport", "", "Denmark", "DX"],
    ["DHL International", "", "Bahrain", "ES"],
    ["DHL de Guatemala", "", "Guatemala", "L3"],
    ["Daallo Airlines", "", "Djibouti", "D3"],
    ["Dagestan Airlines", "", "Russia", "N2"],
    ["Dalavia", "", "Russia", "H8"],
    ["Darwin Airline", "", "Switzerland", "0D"],
    ["Dauair", "", "Germany", "D5"],
    ["Delta Air Lines", "", "United States", "DL"],
    ["Deutsche Bahn", "", "Germany", "2A"],
    ["Deutsche Rettungsflugwacht", "", "Germany", "1I"],
    ["Dinar", "", "Argentina", "D7"],
    ["Dirgantara Air Service", "", "Indonesia", "AW"],
    ["Discovery Airways", "", "United States", "DH"],
    ["Djibouti Airlines", "", "Djibouti", "D8"],
    ["Dominicana de Aviaci", "", "Dominican Republic", "DO"],
    ["Domodedovo Airlines", "", "Russia", "E3"],
    ["DonbassAero", "", "Ukraine", "5D"],
    ["Dragonair", "", "DRAGON", "KA"],
    ["Druk Air", "", "Bhutan", "KB"],
    ["dba", "", "Germany", "DI"],
    ["Electronic Data Systems", "", "Switzerland", "1C"],
    ["EUjet", "", "Ireland", "VE"],
    ["EVA Air", "", "Taiwan", "BR"],
    ["Eagle Air", "", "Uganda", "H7"],
    ["East African", "", "Uganda", "QU"],
    ["East African Safari Air", "", "Kenya", "S9"],
    ["Eastern Airways", "", "United Kingdom", "T3"],
    ["Eastland Air", "", "Australia", "DK"],
    ["Eastwind Airlines", "", "United States", "W9"],
    ["Edelweiss Air", "", "Switzerland", "WK"],
    ["Egyptair", "", "Egypt", "MS"],
    ["El Al Israel Airlines", "", "Israel", "LY"],
    ["El-Buraq Air Transport", "", "Libya", "UZ"],
    ["Emirates", "Emirates Airlines", "United Arab Emirates", "EK"],
    ["Empire Airlines", "", "United States", "EM"],
    ["Empresa Ecuatoriana De Aviacion", "", "Ecuador", "EU"],
    ["Enkor JSC", "", "Russia]]", "G8"],
    ["Eos Airlines", "", "United States", "E0"],
    ["Eritrean Airlines", "", "Eritrea", "B8"],
    ["Estafeta Carga Aerea", "", "Mexico", "E7"],
    ["Estonian Air", "", "Estonia", "OV"],
    ["Ethiopian Airlines", "", "Ethiopia", "ET"],
    ["Etihad Airways", "", "United Arab Emirates", "EY"],
    ["Euro Exec Express", "", "Sweden", "RZ"],
    ["Eurocypria Airlines", "", "Cyprus", "UI"],
    ["Eurofly Service", "", "Italy", "GJ"],
    ["Eurolot", "", "Poland", "K2"],
    ["Euromanx Airways", "", "Austria", "3W"],
    ["European Air Express", "", "Germany", "EA"],
    ["European Air Transport", "", "Belgium", "QY"],
    ["European Aviation Air Charter", "", "United Kingdom", "E7"],
    ["Eurowings", "", "Germany", "EW"],
    ["Evergreen International Airlines", "", "United States", "EZ"],
    ["Excel Airways", "", "United Kingdom", "JN"],
    ["Execair Aviation", "", "Canada", "MB"],
    ["Executive Airlines", "", "United States", "OW"],
    ["Expo Aviation", "", "Sri Lanka", "8D"],
    ["Express One International", "", "United States", "EO"],
    ["ExpressJet", "", "United States", "XE"],
    ["easyJet", "EasyJet Airline", "United Kingdom", "U2"],
    ["Falcon Aviation", "", "Sweden", "IH"],
    ["Far Eastern Air Transport", "", "Taiwan", "EF"],
    ["Faroejet", "", "Faroe Islands", "F6"],
    ["Faso Airways", "", "Burkina Faso", "F3"],
    ["Federal Express", "", "United States", "FX"],
    ["Fika Salaama Airlines", "", "Uganda", "N8"],
    ["Finalair Congo", "", "Republic of the Congo", "4S"],
    ["Finnair", "", "Finland", "AY"],
    ["Finncomm Airlines", "", "Finland", "FC"],
    ["Firefly", "", "Malaysia", "FY"],
    ["First Air", "", "Canada", "7F"],
    ["First Choice Airways", "", "United Kingdom", "DP"],
    ["Fischer Air", "", "Czech Republic", "8F"],
    ["Flightline", "", "United Kingdom", "B5"],
    ["Florida Coastal Airlines", "", "United States", "PA"],
    ["Florida West International Airways", "", "United States", "RF"],
    ["Fly Air", "", "Turkey", "F2"],
    ["Fly Me Sweden", "", "Sweden", "SH"],
    ["AirAsia X", "FlyAsianXpress", "Malaysia", "D7"],
    ["FlyLal", "", "Lithuania", "TE"],
    ["FlyNordic", "", "Sweden", "LF"],
    ["Flybaboo", "", "Switzerland", "F7"],
    ["Flybe", "", "United Kingdom", "BE"],
    ["Flyglobespan", "", "United Kingdom", "B4"],
    ["Formosa Airlines", "", "Taiwan", "VY"],
    ["Forward Air International Airlines", "", "United States", "BN"],
    ["Four Star Aviation / Four Star Cargo", "", "United States", "HK"],
    ["Freedom Air", "", "United States", "FP"],
    ["Frontier Airlines", "", "United States", "F9"],
    ["Frontier Flying Service", "", "United States", "2F"],
    ["Futura International Airways", "", "Spain", "FH"],
    ["GB Airways", "", "United Kingdom", "GT"],
    ["Galaxy Air", "", "Kyrgyzstan", "7O"],
    ["Galileo International", "", "United States", "1G"],
    ["Gambia International Airlines", "", "Gambia", "GC"],
    ["Gandalf Airlines", "", "Italy", "G7"],
    ["Garuda Indonesia", "", "Indonesia", "GA"],
    ["Gazpromavia", "", "Russia", "4G"],
    ["Gemini Air Cargo", "", "United States", "GR"],
    ["Georgian Airways", "", "Georgia", "A9"],
    ["Georgian National Airlines", "", "Georgia", "QB"],
    ["Germania", "", "Germany", "ST"],
    ["Germanwings", "", "Germany", "4U"],
    ["Gestair", "", "Spain", "GP"],
    ["Ghana International Airlines", "", "Ghana", "G0"],
    ["Go Air", "", "India", "G8"],
    ["Go One Airways", "", "United Kingdom", "GK"],
    ["GoJet Airlines", "", "United States", "G7"],
    ["Gol Transportes Aéreos", "", "Brazil", "G3"],
    ["Golden Air", "", "Sweden", "DC"],
    ["Gorkha Airlines", "", "Nepal", "G1"],
    ["Grant Aviation", "", "United States", "GS"],
    ["Great Lakes Airlines", "", "United States", "ZK"],
    ["Great Wall Airlines", "", "China", "IJ"],
    ["Grupo TACA", "TACA", "Costa Rica", "TA"],
    ["Guine Bissaur Airlines", "", "Guinea-Bissau", "G6"],
    ["Guinee Airlines", "", "Guinea", "J9"],
    ["Gujarat Airways", "", "India", "G8"],
    ["Gulf Air Bahrain", "", "Bahrain", "GF"],
    ["Guyana Airways 2000", "", "", "GY"],
    ["Hageland Aviation Services", "", "United States", "H6"],
    ["Hahn Air", "", "Germany", "HR"],
    ["Hainan Airlines", "", "China", "HU"],
    ["Hainan Phoenix Information Systems", "", "China", "1R"],
    ["Haiti Ambassador Airlines", "", "Haiti", "2T"],
    ["Hamburg International", "", "Germany", "4R"],
    ["TUIfly", "", "Germany", "X3"],
    ["Hapagfly", "", "Germany", "HF"],
    ["Harbor Airlines", "", "United States", "HB"],
    ["Harmony Airways", "", "Canada", "HQ"],
    ["Hawaiian Airlines", "", "United States", "HA"],
    ["Hawaiian Pacific Airlines", "", "United States", "HP"],
    ["Hawkair", "", "Canada", "BH"],
    ["Heavylift Cargo Airlines", "", "Australia", "HN"],
    ["Heli France", "", "France", "8H"],
    ["Helijet", "", "Canada", "JB"],
    ["Helios Airways", "", "Cyprus", "ZU"],
    ["Hellas Jet", "", "Greece", "T4"],
    ["Hello", "", "Switzerland", "HW"],
    ["Helvetic Airways", "", "Switzerland", "2L"],
    ["Hemus Air", "", "Bulgaria", "DU"],
    ["Hewa Bora Airways", "", "Democratic Republic of the Congo", "EO"],
    ["Hex'Air", "", "France", "UD"],
    ["Hi Fly", "", "Portugal", "5K"],
    ["Hokkaido International Airlines", "", "Japan", "HD"],
    ["Hola Airlines", "", "Spain", "H5"],
    ["Hong Kong Airlines", "", "Hong Kong SAR of China", "HX"],
    ["Hong Kong Express Airways", "", "Hong Kong SAR of China", "UO"],
    ["Hope Air", "", "Canada", "HH"],
    ["Horizon Air", "Horizon Airlines", "United States", "QX"],
    ["Horizon Airlines", "", "Australia", "BN"],
    ["Héli Sécurité Helicopter Airlines", "", "France", "H4"],
    ["IBC Airways", "", "United States", "II"],
    ["ICAR Airlines", "", "Ukraine", "C3"],
    ["INFINI Travel Information", "", "Japan", "1F"],
    ["ITA Software", "", "United States", "1U"],
    ["Iberia Airlines", "", "Spain", "IB"],
    ["Iberworld", "", "Spain", "TY"],
    ["Ibex Airlines", "", "Japan", "FW"],
    ["Icelandair", "", "Iceland", "FI"],
    ["Imair Airlines", "", "Azerbaijan", "IK"],
    ["Independence Air", "", "United States", "DH"],
    ["IndiGo Airlines", "", "India", "6E"],
    ["Indian Airlines", "", "India", "IC"],
    ["Indigo", "", "United States", "I9"],
    ["Indonesia AirAsia", "", "Indonesia", "QZ"],
    ["Indonesian Airlines", "", "Indonesia", "IO"],
    ["InteliJet Airways", "", "Colombia", "IJ"],
    ["Inter Islands Airlines", "", "Cape Verde", "H4"],
    ["Interair South Africa", "", "South Africa", "D6"],
    ["Interavia Airlines", "", "Russia", "ZA"],
    ["Intercontinental de Aviaci", "", "Colombia", "RS"],
    ["Interlink Airlines", "", "South Africa", "ID"],
    ["International Business Air", "", "Sweden", "6I"],
    ["Intersky", "", "Austria", "3L"],
    ["Interstate Airline", "", "Netherlands", "I4"],
    ["Iran Air", "", "Iran", "IR"],
    ["Iran Aseman Airlines", "", "Iran", "EP"],
    ["Iraqi Airways", "", "Iraq", "IA"],
    ["Island Airlines", "", "United States", "IS"],
    ["Island Express", "", "United States", "2S"],
    ["Cargo Plus Aviation", "", "United Arab Emirates", "8L"],
    ["Islands Nationair", "", "Papua New Guinea", "CN"],
    ["Islas Airways", "", "Spain", "IF"],
    ["Islena De Inversiones", "", "Honduras", "WC"],
    ["Israir", "", "Israel", "6H"],
    ["Itali Airlines", "", "Italy", "9X"],
    ["Itek Air", "", "Kyrgyzstan", "GI"],
    ["Izair", "", "Turkey", "H9"],
    ["JAL Express", "", "Japan", "JC"],
    ["JALways", "", "Japan", "JO"],
    ["JSC Transport Automated Information Systems", "", "Russia", "1M"],
    ["Japan Airlines", "JAL Japan Airlines", "Japan", "JL"],
    ["Japan Airlines Domestic", "", "Japan", "JL"],
    ["Japan Asia Airways", "", "Japan", "EG"],
    ["Japan Transocean Air", "", "Japan", "NU"],
    ["Jat Airways", "", "Serbia", "JU"],
    ["Jatayu Airlines", "", "Indonesia", "VJ"],
    ["Jazeera Airways", "", "Kuwait", "J9"],
    ["Jeju Air", "", "Republic of Korea", "7C"],
    ["Jet Airways", "", "India", "9W"],
    ["Jet Airways", "", "United States", "QJ"],
    ["Jetclub", "", "Switzerland", "0J"],
    ["Jetstar Asia Airways", "", "Singapore", "3K"],
    ["Jet2.com", "", "United Kingdom", "LS"],
    ["Jet4You", "", "Morocco", "8J"],
    ["JetBlue Airways", "", "United States", "B6"],
    ["Jetairfly", "", "Belgium", "JF"],
    ["Jetclub", "", "Switzerland", "0J"],
    ["JetsGo", "", "Canada", "SG"],
    ["Jetstar Airways", "", "Australia", "JQ"],
    ["Jett8 Airlines Cargo", "", "Singapore", "JX"],
    ["Jetx Airlines", "", "Iceland", "GX"],
    ["Jordan Aviation", "", "Jordan", "R5"],
    ["Juneyao Airlines", "", "China", "HO"],
    ["KD Avia", "", "Russia", "KD"],
    ["KLM Cityhopper", "", "Netherlands", "WA"],
    ["KLM Royal Dutch Airlines", "", "Netherlands", "KL"],
    ["Kabo Air", "", "Nigeria", "N2"],
    ["Kalitta Air", "", "United States", "K4"],
    ["Kam Air", "", "Afghanistan", "RQ"],
    ["Kampuchea Airlines", "", "Cambodia", "E2"],
    ["Karat", "", "Russia", "V2"],
    ["Kavminvodyavia", "", "Russia", "KV"],
    ["Kenmore Air", "", "United States", "M5"],
    ["Kenya Airways", "", "Kenya", "KQ"],
    ["Keystone Air Services", "", "Canada", "BZ"],
    ["Kingfisher Airlines", "", "India", "IT"],
    ["Kish Air", "", "Iran", "Y9"],
    ["Kiwi International Air Lines", "", "United States", "KP"],
    ["Kogalymavia Air Company", "", "Russia", "7K"],
    ["Komiinteravia", "", "Russia", "8J"],
    ["Korean Air", "", "Republic of Korea", "KE"],
    ["Krasnojarsky Airlines", "", "Russia", "7B"],
    ["Krylo Airlines", "", "Russia", "K9"],
    ["Kuban Airlines", "", "Russia", "GW"],
    ["Kunpeng Airlines", "", "China", "VD"],
    ["Kuwait Airways", "", "Kuwait", "KU"],
    ["Kuzu Airlines Cargo", "", "Turkey", "GO"],
    ["Kyrgyz Airlines", "", "Kyrgyzstan", "N5"],
    ["Kyrgyzstan", "", "Kyrgyzstan", "QH"],
    ["Kyrgyzstan Airlines", "", "Kyrgyzstan", "R8"],
    ["Kibris T", "", "Turkey", "KY"],
    ["L.A.B. Flying Service", "", "United States", "JF"],
    ["LACSA", "", "Costa Rica", "LR"],
    ["LAI - Linea Aerea IAACA", "", "Venezuela", "KG"],
    ["LAN Airlines", "", "Chile", "LA"],
    ["LAN Argentina", "", "Argentina", "4M"],
    ["LAN Express", "", "Chile", "LU"],
    ["LAN Peru", "", "Peru", "LP"],
    ["LOT Polish Airlines", "", "Poland", "LO"],
    ["LTE International Airways", "", "Spain", "XO"],
    ["LTU Austria", "", "Austria", "L3"],
    ["LTU International", "", "Germany", "LT"],
    ["Lagun Air", "", "Spain", "N6"],
    ["Lankair", "", "Sri Lanka", "IK"],
    ["Lao Airlines", "", "Lao Peoples Democratic Republic", "QV"],
    ["Laoag International Airlines", "", "Philippines", "L7"],
    ["Lauda Air", "", "Austria", "NG"],
    ["Lebanese Air Transport", "", "Lebanon", "LQ"],
    ["Leeward Islands Air Transport", "", "Antigua and Barbuda", "LI"],
    ["Libyan Arab Airlines", "", "Libya", "LN"],
    ["Linea Aerea SAPSA", "", "Chile", "L7"],
    ["Linea Aerea de Servicio Ejecutivo Regional", "", "Venezuela", "8z"],
    ["Linea Turistica Aerotuy", "", "Venezuela", "LD"],
    ["Lineas Aereas Azteca", "", "Mexico", "ZE"],
    ["Linhas A", "", "Mozambique", "LM"],
    ["Lion Mentari Airlines", "", "Indonesia", "JT"],
    ["Livingston", "", "Italy", "LM"],
    ["Lloyd Aereo Boliviano", "", "Bolivia", "LB"],
    ["Luftfahrtgesellschaft Walter", "", "Germany", "HE"],
    ["Lufthansa", "", "Germany", "LH"],
    ["Lufthansa Cargo", "", "Germany", "LH"],
    ["Lufthansa CityLine", "", "Germany", "CL"],
    ["Lufthansa Systems", "", "Germany", "L1"],
    ["Lufttaxi Fluggesellschaft", "", "Germany", "DV"],
    ["Lufttransport", "", "Norway", "L5"],
    ["Luxair", "", "Luxembourg", "LG"],
    ["Lviv Airlines", "", "Ukraine", "5V"],
    ["Lynden Air Cargo", "", "United States", "L2"],
    ["L", "", "Argentina", "MJ"],
    ["MasAir", "", "Mexico", "M7"],
    ["MAT Macedonian Airlines", "", "Macedonia", "IN"],
    ["MIAT Mongolian Airlines", "", "Mongolia", "OM"],
    ["MNG Airlines", "", "Turkey", "MB"],
    ["Macair Airlines", "", "Australia", "CC"],
    ["Maersk", "", "Denmark", "DM"],
    ["Mahan Air", "", "Iran", "W5"],
    ["Mahfooz Aviation", "", "Gambia", "M2"],
    ["Malaysia Airlines", "", "Malaysia", "MH"],
    ["Malmö Aviation", "", "Sweden", "TF"],
    ["Malta Air Charter", "", "Malta", "R5"],
    ["Malév", "", "Hungary", "MA"],
    ["Mandala Airlines", "", "Indonesia", "RI"],
    ["Mandarin Airlines", "", "Taiwan", "AE"],
    ["Mango", "", "South Africa", "JE"],
    ["Mars RK", "", "Ukraine", "6V"],
    ["Marsland Aviation", "", "Sudan", "M7"],
    ["Martinair", "", "Netherlands", "MP"],
    ["Mastertop Linhas Aereas", "", "Brazil", "Q4"],
    ["Mavial Magadan Airlines", "", "Russia", "H5"],
    ["Maxair", "", "Sweden", "8M"],
    ["Maxjet Airways", "", "United States", "MY"],
    ["Maya Island Air", "", "Belize", "MW"],
    ["Menajet", "", "Lebanon", "IM"],
    ["Meridiana", "", "Italy", "IG"],
    ["Merpati Nusantara Airlines", "", "Indonesia", "MZ"],
    ["Mesa Airlines", "", "United States", "YV"],
    ["Mesaba Airlines", "", "United States", "XJ"],
    ["Mexicana de Aviaci", "", "Mexico", "MX"],
    ["Miami Air International", "", "United States", "GL"],
    ["Middle East Airlines", "", "Lebanon", "ME"],
    ["Midway Airlines", "", "United States", "JI"],
    ["Midwest Airlines", "", "United States", "YX"],
    ["Midwest Airlines (Egypt)", "", "Egypt", "MY"],
    ["Moldavian Airlines", "", "Moldova", "2M"],
    ["Monarch Airlines", "", "United Kingdom", "ZB"],
    ["Myway Airlines", "", "Italy", "8I"],
    ["Montenegro Airlines", "", "Montenegro", "YM"],
    ["Moskovia Airlines", "", "Russia", "3R"],
    ["Motor Sich", "", "Ukraine", "M9"],
    ["Mount Cook Airlines", "", "New Zealand", "NM"],
    ["Mountain Air Company", "", "Sierra Leone", "N4"],
    ["MyTravel Airways", "", "United Kingdom", "VZ"],
    ["Myanma Airways", "", "Myanmar", "UB"],
    ["Myanmar Airways International", "", "Myanmar", "8M"],
    ["Nantucket Airlines", "", "United States", "DV"],
    ["Nas Air", "", "Mali", "P9"],
    ["Nasair", "", "Eritrea", "UE"],
    ["National Airlines", "", "Chile", "N4"],
    ["National Airlines", "", "United States", "N7"],
    ["National Airlines", "", "United States", "NA"],
    ["National Airways Cameroon", "", "Cameroon", "9O"],
    ["National Jet Systems", "", "Australia", "NC"],
    ["Nationwide Airlines", "", "South Africa", "CE"],
    ["Nauru Air Corporation", "", "Nauru", "ON"],
    ["Navitaire", "", "United States", "1N"],
    ["Nepal Airlines", "", "Nepal", "RA"],
    ["Neos", "", "Italy", "NO"],
    ["NetJets", "", "United States", "1I"],
    ["New England Airlines", "", "United States", "EJ"],
    ["NextJet", "", "Sweden", "2N"],
    ["Niki", "", "Austria", "HG"],
    ["Nippon Cargo Airlines", "", "Japan", "KZ"],
    ["Nok Air", "", "Thailand", "DD"],
    ["Nordeste Linhas Aereas Regionais", "", "Brazil", "JH"],
    ["Nordic Regional", "", "Sweden", "6N"],
    ["North Coast Aviation", "", "Papua New Guinea", "N9"],
    ["North Flying", "", "Denmark", "M3"],
    ["North-Wright Airways", "", "Canada", "HW"],
    ["Northern Air Cargo", "", "United States", "NC"],
    ["Northern Dene Airways", "", "Canada", "U7"],
    ["Northwest Airlines", "", "United States", "NW"],
    ["Northwest Regional Airlines", "", "Australia", "FY"],
    ["Northwestern Air", "", "Canada", "J3"],
    ["Norwegian Air Shuttle", "", "Norway", "DY"],
    ["Nouvel Air Tunisie", "", "Tunisia", "BJ"],
    ["Nova Airline", "", "Sudan", "M4"],
    ["Novair", "", "Sweden", "1I"],
    ["Nuevo Continente", "", "Peru", "N6"],
    ["Nas Air", "", "Saudi Arabia", "XY"],
    ["O'Connor Airlines", "", "Australia", "UQ"],
    ["OAG", "", "United Kingdom", "CR"],
    ["Oasis Hong Kong Airlines", "", "Hong Kong", "O8"],
    ["Ocean Airlines", "", "Italy", "VC"],
    ["Oceanair", "", "Brazil", "O6"],
    ["Oceanic Airlines", "", "Guinea", "O2"],
    ["Olympic Airlines", "", "Greece", "OA"],
    ["Oman Air", "", "Oman", "WY"],
    ["Omni Air International", "", "United States", "OY"],
    ["Omskavia Airline", "", "Russia", "N3"],
    ["Onur Air", "", "Turkey", "8Q"],
    ["Orenburg Airlines", "", "Russia", "R2"],
    ["Orient Thai Airlines", "", "Thailand", "OX"],
    ["Origin Pacific Airways", "", "New Zealand", "QO"],
    ["Ostfriesische Lufttransport", "", "Germany", "OL"],
    ["Our Airline", "", "Nauru", "ON"],
    ["Overland Airways", "", "Nigeria", "OJ"],
    ["Ozark Air Lines", "", "United States", "OZ"],
    ["Ozjet Airlines", "", "Australia", "O7"],
    ["PAN Air", "", "Spain", "PV"],
    ["PB Air", "", "Thailand", "9Q"],
    ["PLUNA", "", "Uruguay", "PU"],
    ["PMTair", "", "Cambodia", "U4"],
    ["Pace Airlines", "", "United States", "Y5"],
    ["Jetstar Pacific", "Pacific Airlines", "Vietnam", "BL"],
    ["Pacific Blue", "", "New Zealand", "DJ"],
    ["Pacific Coastal Airline", "", "Canada", "8P"],
    ["Pacific East Asia Cargo Airlines", "", "Philippines", "Q8"],
    ["Pacific Southwest Airlines", "", "United States", "PS"],
    ["Pacific Wings", "", "United States", "LW"],
    ["Pacificair", "", "Philippines", "GX"],
    ["Pakistan International Airlines", "PIA Pakistan International", "Pakistan", "PK"],
    ["Palau Trans Pacific Airline", "", "Palau", "GP"],
    ["Palestinian Airlines", "", "Egypt", "PF"],
    ["Pamir Airways", "", "Afghanistan", "NR"],
    ["Pan American Airways", "", "United States", "PA"],
    ["Pan American World Airways", "", "United States", "PA"],
    ["Panafrican Airways", "", "Ivory Coast", "PQ"],
    ["Pantanal Linhas Aéreas", "", "Brazil", "P8"],
    ["Paramount Airways", "", "India", "I7"],
    ["Pearl Airways", "", "Haiti", "HP"],
    ["Pegasus Airlines", "", "Turkey", "PC"],
    ["Pegasus Hava Tasimaciligi", "", "Turkey", "1I"],
    ["Peninsula Airways", "", "United States", "KS"],
    ["Perm Airlines", "", "Russia", "P9"],
    ["Philippine Airlines", "", "Philippines", "PR"],
    ["Phoenix Airways", "", "Switzerland", "HP"],
    ["Phuket Air", "", "Thailand", "9R"],
    ["Piedmont Airlines (1948-1989)", "", "United States", "PI"],
    ["Pinnacle Airlines", "", "United States", "9E"],
    ["Polar Air Cargo", "", "United States", "PO"],
    ["Polynesian Airlines", "", "Samoa", "PH"],
    ["Polynesian Blue", "", "New Zealand", "DJ"],
    ["Polyot Sirena", "", "Russia", "1U"],
    ["Porter Airlines", "", "Canada", "PD"],
    ["Portugalia", "", "Portugal", "NI"],
    ["Potomac Air", "", "United States", "BK"],
    ["Precision Air", "", "Tanzania", "PW"],
    ["President Airlines", "null", "Cambodia", "TO"],
    ["Primaris Airlines", "", "United States", "FE"],
    ["Princess Air", "", "", "8Q"],
    ["Private Wings Flugcharter", "", "Germany", "8W"],
    ["Proflight Commuter Services", "", "Zambia", "P0"],
    ["Qantas", "Qantas Airways", "Australia", "QF"],
    ["Qatar Airways", "", "Qatar", "QR"],
    ["RACSA", "", "Guatemala", "R6"],
    ["Radixx Solutions International", "", "United States", "1D"],
    ["Redhill Aviation", "", "United Kingdom", "8L"],
    ["Reem Air", "", "Kyrgyzstan", "V4"],
    ["Regional Airlines", "", "Morocco", "FN"],
    ["Regional Express", "", "Australia", "ZL"],
    ["RegionsAir", "", "United States", "3C"],
    ["Reno Air", "", "United States", "QQ"],
    ["Republic Airlines", "", "United States", "RW"],
    ["Republic Express Airlines", "", "Indonesia", "RH"],
    ["Rico Linhas A", "", "Brazil", "C7"],
    ["Rio Grande Air", "", "United States", "E2"],
    ["Rio Sul Servi", "", "Brazil", "SL"],
    ["Rossiya", "", "Russia", "R4"],
    ["Air Rarotonga", "", "Cook Islands", "GZ"],
    ["Royal Air Force", "", "United Kingdom", "RR"],
    ["Royal Air Force of Oman", "", "Oman", "RS"],
    ["Royal Air Maroc", "", "Morocco", "AT"],
    ["Royal Airlines", "", "Pakistan", "R0"],
    ["Royal Aruban Airline", "", "Aruba", "V5"],
    ["Royal Brunei Airlines", "", "Brunei", "BI"],
    ["Royal Jordanian", "", "Jordan", "RJ"],
    ["Royal Khmer Airlines", "", "Cambodia", "RK"],
    ["Royal Nepal Airlines", "", "Nepal", "RA"],
    ["Royal Tongan Airlines", "", "Tonga", "WR"],
    ["Russian Sky Airlines", "", "Russia", "P7"],
    ["Rwandair Express", "", "Rwanda", "WB"],
    ["Ryan International Airlines", "", "United States", "RD"],
    ["Ryanair", "", "Ireland", "FR"],
    ["Régional", "", "France", "YS"],
    ["SATA International", "", "Portugal", "S4"],
    ["South African Airways", "SAA South African Airways", "South Africa", "SA"],
    ["Shaheen Air International", "", "Pakistan", "NL"],
    ["Scandinavian Airlines System", "SAS Scandinavian Airlines", "Sweden", "SK"],
    ["S7 Airlines", "Sibir Airlines", "Russia", "S7"],
    ["Seaborne Airlines", "", "United States", "BB"],
    ["SriLankan Airlines", "", "Sri Lanka", "UL"],
    ["Sun Country Airlines", "", "United States", "SY"],
    ["Sky Express", "", "Greece", "G3"],
    ["Spicejet", "", "India", "SG"],
    ["Sky Eyes", "", "Thailand", "I6"],
    ["SAETA", "", "Ecuador", "EH"],
    ["Star Flyer", "", "Japan", "7G"],
    ["Safair", "", "South Africa", "FA"],
    ["Skagway Air Service", "", "United States", "N5"],
    ["SATA Air Acores", "", "Portugal", "SP"],
    ["Scorpio Aviation", "", "", "8S"],
    ["Singapore Airlines", "", "Singapore", "SQ"],
    ["Sibaviatrans", "", "Russia", "5M"],
    ["Skynet Airlines", "", "Ireland", "SI"],
    ["SITA", "", "Belgium", "XS"],
    ["Sriwijaya Air", "", "Indonesia", "SJ"],
    ["Sama Airlines", "", "Saudi Arabia", "ZS"],
    ["Singapore Airlines Cargo", "", "Singapore", "SQ"],
    ["Siem Reap Airways", "", "Cambodia", "FT"],
    ["Sky Work Airlines", "SkyWork", "Switzerland", "SX"],
    ["Swedline Express", "", "Sweden", "SM"],
    ["South East Asian Airlines", "", "Philippines", "DG"],
    ["SwedJet Airways", "", "Sweden", "VD"],
    ["Skyservice Airlines", "", "Canada", "5G"],
    ["Servicios de Transportes A", "", "Argentina", "FS"],
    ["Sudan Airways", "", "Sudan", "SD"],
    ["Sun Air (Fiji)", "", "Fiji", "PI"],
    ["Sun Air of Scandinavia", "", "Denmark", "EZ"],
    ["Saudi Arabian Airlines", "", "Saudi Arabia", "SV"],
    ["Southwest Airlines", "", "United States", "WN"],
    ["Southern Winds Airlines", "", "Argentina", "A4"],
    ["Sunwing Airlines", "", "Canada", "WG"],
    ["Swiss International Air Lines", "Swiss Airlines", "Switzerland", "LX"],
    ["Swissair", "", "Switzerland", "SR"],
    ["Swe Fly", "", "Sweden", "WV"],
    ["Shovkoviy Shlyah", "", "Ukraine", "S8"],
    ["SunExpress", "", "Turkey", "XQ"],
    ["Syrian Arab Airlines", "", "Syrian Arab Republic", "RB"],
    ["Skywalk Airlines", "", "United States", "AL"],
    ["Silk Way Airlines", "", "Azerbaijan", "ZP"],
    ["Samara Airlines", "", "Russia", "E5"],
    ["Shandong Airlines", "", "China", "SC"],
    ["Spring Airlines", "", "China", "9S"],
    ["Sichuan Airlines", "", "China", "3U"],
    ["Shanghai Airlines", "", "China", "FM"],
    ["Shenzhen Airlines", "", "China", "ZH"],
    ["Shanxi Airlines", "", "China", "8C"],
    ["Sun D'Or", "", "Israel", "7L"],
    ["SkyEurope", "", "Slovakia", "NE"],
    ["Sunshine Express Airlines", "", "Australia", "CQ"],
    ["Superior Aviation", "", "United States", "SO"],
    ["Spanair", "", "Spain", "JK"],
    ["San Juan Airlines", "", "United States", "2G"],
    ["Sabre Pacific", "", "Australia", "1Z"],
    ["Sabre", "", "United States", "1S"],
    ["Sierra Nevada Airlines", "", "United States", "1I"],
    ["Siren-Travel", "", "Russia", "1H"],
    ["Sirena", "", "Russia", "1Q"],
    ["Sky Trek International Airlines", "", "", "1I"],
    ["Southern Cross Distribution", "", "Australia", "1K"],
    ["Sutra", "", "United States", "1K"],
    ["SNCF", "", "France", "2C"],
    ["Star Equatorial Airlines", "", "Guinea", "2S"],
    ["Spirit Airlines", "", "United States", "NK"],
    ["SATENA", "", "Colombia", "9R"],
    ["Slok Air Gambia", "", "Gambia", "S0"],
    ["Sosoliso Airlines", "", "Nigeria", "SO"],
    ["Sky Trek International Airlines", "", "United States", "1I"],
    ["Skybus Airlines", "", "United States", "SX"],
    ["SkyKing Turks and Caicos Airways", "", "Turks and Caicos Islands", "RU"],
    ["Santa Barbara Airlines", "", "Venezuela", "S3"],
    ["Sky Airline", "", "Chile", "H2"],
    ["SkyWest", "", "United States", "OO"],
    ["Skyways Express", "", "Sweden", "JZ"],
    ["Skymark Airlines", "", "Japan", "BC"],
    ["Sierra National Airlines", "", "Sierra Leone", "LJ"],
    ["SilkAir", "", "Singapore", "MI"],
    ["Slovak Airlines", "", "Slovakia", "6Q"],
    ["Surinam Airways", "", "Suriname", "PY"],
    ["Servant Air", "", "United States", "8D"],
    ["Sterling Airlines", "", "Denmark", "NB"],
    ["Skynet Asia Airways", "", "Japan", "6J"],
    ["Solomon Airlines", "", "Solomon Islands", "IE"],
    ["Saratov Aviation Division", "", "Russia", "6W"],
    ["Sat Airlines", "", "Kazakhstan", "HZ"],
    ["Shuttle America", "", "United States", "S5"],
    ["Scat Air", "", "Kazakhstan", "DV"],
    ["Sirin", "", "", "R1"],
    ["Star Air", "", "Denmark", "S6"],
    ["TAME", "", "Ecuador", "EQ"],
    ["TAM Brazilian Airlines", "", "Brazil", "JJ"],
    ["TAP Portugal", "TAP Air Portugal", "Portugal", "TP"],
    ["Tunisair", "", "Tunisia", "TU"],
    ["TNT Airways", "", "Belgium", "3V"],
    ["Tropical Airways", "", "Haiti", "M7"],
    ["Thai Air Cargo", "", "Thailand", "T2"],
    ["Thomas Cook Airlines", "", "Belgium", "FQ"],
    ["Thomas Cook Airlines", "", "United Kingdom", "MT"],
    ["Tandem Aero", "", "Moldova", "TQ"],
    ["Teamline Air", "", "Austria", "L9"],
    ["Transeuropean Airlines", "", "Russia", "UE"],
    ["Titan Airways", "", "United Kingdom", "ZT"],
    ["Tiger Airways", "", "Singapore", "TR"],
    ["Tiger Airways Australia", "", "Australia", "TT"],
    ["Thai Airways International", "", "Thailand", "TG"],
    ["Thai AirAsia", "Thai Air Asia", "Thailand", "FD"],
    ["Turkish Airlines", "", "Turkey", "TK"],
    ["Twin Jet", "", "France", "T7"],
    ["Thai Sky Airlines", "", "Thailand", "9I"],
    ["Tulip Air", "", "Netherland", "TD"],
    ["Trans Mediterranean Airlines", "", "Lebanon", "TL"],
    ["Tri-MG Intra Asia Airlines", "", "Indonesia", "GY"],
    ["Tiara Air", "", "Aruba", "3P"],
    ["Tobruk Air", "", "Libya", "7T"],
    ["Tol-Air Services", "", "United States", "TI"],
    ["Thomsonfly", "", "United Kingdom", "BY"],
    ["Tropic Air", "", "Belize", "PM"],
    ["Tower Air", "", "United States", "FF"],
    ["TAMPA", "", "Colombia", "QT"],
    ["TransAsia Airways", "", "Taiwan", "GE"],
    ["Transavia Holland", "", "Netherlands", "HV"],
    ["TACV", "", "Portugal", "VR"],
    ["TransMeridian Airlines", "", "United States", "T9"],
    ["Transmile Air Services", "", "Malaysia", "TH"],
    ["Trast Aero", "", "Kyrgyzstan", "S5"],
    ["Transwest Air", "", "Canada", "9T"],
    ["Transaero Airlines", "", "Russia", "UN"],
    ["Thai Star Airlines", "", "Thailand", "T9"],
    ["Turkmenistan Airlines", "Turkmenhovayollary", "Turkmenistan", "T5"],
    ["Tuninter", "", "Tunisia", "UG"],
    ["Tavrey Airlines", "", "Ukraine", "T6"],
    ["Travel Service", "", "Czech Republic", "QS"],
    ["Trans World Airlines", "TWA", "United States", "TW"],
    ["Transaviaexport", "", "Belarus", "AL"],
    ["TUIfly Nordic", "", "Sweden", "6B"],
    ["TAAG Angola Airlines", "", "Angola", "DT"],
    ["Tassili Airlines", "", "Algeria", "SF"],
    ["TAM Mercosur", "", "Paraguay", "PZ"],
    ["Trans States Airlines", "", "United States", "AX"],
    ["Travelsky Technology", "", "China", "1E"],
    ["Thalys", "", "Belgium", "2H"],
    ["Open Skies Consultative Commission", "", "United States", "1L"],
    ["Tarom", "", "Romania", "RO"],
    ["Turan Air", "", "Azerbaijan", "3T"],
    ["TRIP Linhas A", "", "Brazil", "8R"],
    ["Transports et Travaux A", "", "", "OF"],
    ["USA3000 Airlines", "", "United States", "U5"],
    ["United Airlines", "", "United States", "UA"],
    ["United Feeder Service", "", "United States", "U2"],
    ["USA Jet Airlines", "", "United States", "U7"],
    ["Ural Airlines", "", "Russia", "U6"],
    ["UM Airlines", "", "Ukraine", "UF"],
    ["Ukrainian Cargo Airways", "", "Ukraine", "6Z"],
    ["United Parcel Service", "", "United States", "5X"],
    ["US Airways", "", "United States", "US"],
    ["UTair Aviation", "", "Russia", "UT"],
    ["Uzbekistan Airways", "", "Uzbekistan", "HY"],
    ["Ukraine International Airlines", "", "Ukraine", "PS"],
    ["US Helicopter Corporation", "", "United States", "UH"],
    ["V Australia Airlines", "", "Australia", "VA"],
    ["Valuair", "", "Singapore", "VF"],
    ["Voyageur Airways", "", "Canada", "VC"],
    ["Vietnam Airlines", "", "Vietnam", "VN"],
    ["VIM Airlines", "", "Russia", "NN"],
    ["VIA Rail Canada", "", "Canada", "2R"],
    ["Viasa", "", "Venezuela", "VA"],
    ["Volaris", "", "Mexico", "Y4"],
    ["Volga-Dnepr Airlines", "", "Russia", "VI"],
    ["Virgin America", "", "United States", "VX"],
    ["Virgin Express", "", "Belgium", "TV"],
    ["Virgin Nigeria Airways", "", "Nigeria", "VK"],
    ["Virgin Atlantic Airways", "", "United Kingdom", "VS"],
    ["Viva Macau", "", "Macao", "ZG"],
    ["Volare Airlines", "", "Italy", "VE"],
    ["Vueling Airlines", "", "Spain", "VY"],
    ["Vladivostok Air", "", "Russia", "XF"],
    ["Varig Log", "", "Brazil", "LC"],
    ["Viaggio Air", "", "Bulgaria", "VM"],
    ["Virgin Australia", "", "Australia", "VA"],
    ["Virgin Blue", "", "Australia", "DJ"],
    ["VRG Linhas Aereas", "Varig", "Brazil", "RG"],
    ["VASP", "", "Brazil", "VP"],
    ["VLM Airlines", "", "Belgium", "VG"],
    ["Wayraper", "", "Peru", "7W"],
    ["WebJet Linhas A", "", "Brazil", "WJ"],
    ["Welcome Air", "", "Austria", "2W"],
    ["West Air Sweden", "", "Sweden", "PT"],
    ["West Coast Air", "", "Canada", "8O"],
    ["WestJet", "", "Canada", "WS"],
    ["Western Airlines", "", "United States", "WA"],
    ["Westward Airways", "", "United States", "CN"],
    ["Widerøe", "", "Norway", "WF"],
    ["Wind Jet", "", "Italy", "IV"],
    ["Wings Air", "", "Indonesia", "IW"],
    ["Wings of Alaska", "", "United States", "K5"],
    ["Wizz Air", "", "Hungary", "W6"],
    ["Wizz Air Hungary", "", "Bulgaria", "8Z"],
    ["World Airways", "", "United States", "WO"],
    ["Worldspan", "", "United States", "1P"],
    ["Wright Air Service", "", "United States", "8V"],
    ["XL Airways France", "", "France", "SE"],
    ["Xiamen Airlines", "", "China", "MF"],
    ["Xtra Airways", "", "United States", "XP"],
    ["Yamal Airlines", "", "Russia", "YL"],
    ["Yangtze River Express", "", "China", "Y8"],
    ["Yemenia", "", "Yemen", "IY"],
    ["Zambian Airways", "", "Zambia", "Q3"],
    ["Zip", "", "Canada", "3J"],
    ["Zimex Aviation", "", "Switzerland", "C4"],
    ["Zoom Airlines", "", "Canada", "Z4"],
    ["buzz", "", "\\N", "UK"],
    ["Maldivian Air Taxi", "", "Maldives", "8Q"],
    ["Sky Express", "SkyExpress", "Russia", "XW"],
    ["Yellow Air Taxi", "", "United States", "Y0"],
    ["Royal Air Cambodge", "", "Cambodia", "VJ"],
    ["Air Mandalay", "", "Burma", "6T"],
    ["TAN-SAHSA", "", "Honduras", "SH"],
    ["Air Busan", "", "Republic of Korea", "BX"],
    ["TUI Airlines Belgium", "now Jetairlfy", "Belgium", "TB"],
    ["Braathens", "Braathens SAFE", "Norway", "BU"],
    ["Globus", "", "Russia", "GH"],
    ["Air Kazakhstan", "", "Kazakhstan", "9Y"],
    ["Japan Air System", "", "Japan", "JD"],
    ["Annsett New Zealand (NZA)", "", "New Zealand", "ZQ"],
    ["EasyJet (DS)", "", "Switzerland", "DS"],
    ["Star Peru (2I)", "", "Peru", "2I"],
    ["Carnival Air Lines", "", "United States", "KW"],
    ["United Airways", "", "Bangladesh", "4H"],
    ["Trans Maldivian Airways", "", "Maldives", "M8"],
    ["Fly540", "", "Kenya", "5H"],
    ["Transavia France", "", "France", "TO"],
    ["Island Air (WP)", "", "United States", "WP"],
    ["1-2-go", "fly 1-2-go", "Thailand", "OG"],
    ["Uni Air", "", "Taiwan", "B7"],
    ["Gomelavia", "", "Belarus", "YD"],
    ["Red Wings", "Avialinii 400", "Russia", "WZ"],
    ["TUIfly (X3)", "", "Germany", "11"],
    ["Felix Airways", "", "Yemen", "FU"],
    ["Kostromskie avialinii", "", "Russia", "K1"],
    ["Greenfly", "", "Spain", "XX"],
    ["Tajik Air", "", "Tajikistan", "7J"],
    ["Air Mozambique", "", "Mozambique", "TM"],
    ["ELK Airways", "", "Estonia", "--"],
    ["Gabon Airlines", "", "Gabon", "GY"],
    ["Maldivo Airlines", "", "Maldives", "ML"],
    ["Virgin Pacific", "", "Fiji", "VH"],
    ["Zest Air", "", "Philippines", "Z2"],
    ["Yangon Airways", "", "Burma", "HK"],
    ["Transport Aérien Transrégional", "TAT", "France", "IJ"],
    ["Minerva Airlines", "", "Italy", "N4"],
    ["Eastar Jet", "", "South Korea", "ZE"],
    ["Jin Air", "", "South Korea", "LJ"],
    ["Aéris (Priv)", "", "France", "SH"],
    ["Air Arabia Maroc", "", "Morocco", "3O"],
    ["Baltic Air lines", "", "Latvia", "B1"],
    ["Ciel Canadien", "", "Canada", "YC"],
    ["Canadian National Airways", "", "Canada", "CN"],
    ["Epic Holiday", "Epic Holidays", "United States", "FA"],
    ["Air Comet Chile", "", "Chile", "3I"],
    ["Nazca", "", "Peru", "-."],
    ["Voronezhskie Airlanes", "", "Russia", "DN"],
    ["Line Blue", "", "Germany", "L8"],
    ["Blue Sky America", "", "United States", "BU"],
    ["Texas Spirit", "", "United States", "XS"],
    ["Illinois Airways", "", "United States", "IL"],
    ["Salzburg arrows", "SZA", "Austria", "SZ"],
    ["Texas Wings", "", "United States", "TQ"],
    ["California Western", "", "United States", "KT"],
    ["Dennis Sky", "Dennis Sky Holding", "Israel", "DH"],
    ["Zz", "", "Belgium", "ZZ"],
    ["Atifly", "", "United States", "A1"],
    ["Air UK", "", "United Kingdom", "UK"],
    ["Suckling Airways", "", "United Kingdom", "CB"],
    ["Reno Sky", "", "United States", "RY"],
    ["Ciao Air", "", "Italy", "99"],
    ["Birmingham European", "", "United Kingdom", "VB"],
    ["Pal airlines", "", "Chile", "5P"],
    ["CanXpress", "", "Canada", "C1"],
    ["Danube Wings (V5)", "", "Slovakia", "V5"],
    ["Sharp Airlines", "", "Australia", "SH"],
    ["CanXplorer", "", "Canada", "C2"],
    ["Click (Mexicana)", "", "Mexico", "QA"],
    ["World Experience Airline", "WEA", "Canada", "W1"],
    ["ALAK", "", "Russia", "J4"],
    ["AJT Air International", "", "Russia", "E9"],
    ["Air Choice One", "", "United States", "3E"],
    ["China United", "", "China", "KN"],
    ["Locair", "", "United States", "ZQ"],
    ["Safi Airlines", "", "Afghanistan", "4Q"],
    ["SeaPort Airlines", "", "United States", "K5"],
    ["Salmon Air", "", "United States", "S6"],
    ["Fly Illi", "", "United States", "IL"],
    ["Bobb Air Freight", "", "Germany", "01"],
    ["Star1 Airlines", "", "Lithuania", "V9"],
    ["Pelita", "", "Indonesia", "6D"],
    ["Alpi Eagles (E8)", "", "Italy", "E8"],
    ["Alaska Seaplane Service", "", "United States", "J5"],
    ["TAN", "", "Argentina", "T8"],
    ["MexicanaLink", "", "Mexico", "I6"],
    ["Island Spirit", "", "Iceland", "IP"],
    ["TACA Peru", "", "Peru", "T0"],
    ["Pan Am World Airways Dominicana", "PAWA Dominicana", "Dominican Republic", "7Q"],
    ["Primera Air", "", "Iceland", "PF"],
    ["Air Antilles Express", "", "Guadeloupe", "3S"],
    ["Regional Paraguaya", "", "Paraguay", "P7"],
    ["VIP Ecuador", "", "Ecuador", "V6"],
    ["Peruvian Airlines", "", "Peru", "P9"],
    ["Polar Airlines", "", "Russia", "ЯП"],
    ["Catovair", "", "Mauritius", "OC"],
    ["Halcyonair", "", "Cape Verde", "7Z"],
    ["Business Aviation", "", "Congo (Kinshasa)", "4P"],
    ["Compagnie Africaine d'Aviation", "", "Congo (Kinshasa)", "E9"],
    ["Zambia Skyways", "", "Zambia", "K8"],
    ["AlMasria Universal Airlines", "", "Egypt", "UJ"],
    ["SmartLynx Airlines", "", "Latvia", "6Y"],
    ["KoralBlue Airlines", "", "Egypt", "K7"],
    ["Elysian Airlines", "", "Cameroon", "E4"],
    ["Hellenic Imperial Airways", "", "Greece", "HT"],
    ["Amsterdam Airlines", "", "Netherlands", "WD"],
    ["Arik Niger", "", "Niger", "Q9"],
    ["Dana Air", "", "Nigeria", "DA"],
    ["STP Airways", "", "Sao Tome and Principe", "8F"],
    ["Med Airways", "", "Lebanon", "7Y"],
    ["Skyjet Airlines", "", "Uganda", "UQ"],
    ["Air Volga", "", "Russia", "G6"],
    ["Royal Falcon", "", "Jordan", "RL"],
    ["Euroline", "", "Georgia", "4L"],
    ["Worldways", "", "Canada", "WG"],
    ["Athens Airways", "", "Greece", "ZF"],
    ["Viking Hellas", "", "Greece", "VQ"],
    ["Starline.kz", "", "Kazakhstan", "DZ"],
    ["Euro Harmony", "Euro Harmony", "Portugal", "EH"],
    ["Lugansk Airlines", "", "Ukraine", "L7"],
    ["Gryphon Airlines", "", "United States", "6P"],
    ["Gadair European Airlines", "", "Spain", "GP"],
    ["Spirit of Manila Airlines", "", "Philippines", "SM"],
    ["Chongqing Airlines", "", "China", "OQ"],
    ["West Air China", "", "China", "PN"],
    ["Falcon Air (IH)", "", "Sweden", "IH"],
    ["QatXpress", "qatXpress", "Qatar", "C3"],
    ["OneChina", "OneChina", "China", "1C"],
    ["NordStar Airlines", "", "Russia", "Y7"],
    ["Joy Air", "", "China", "JR"],
    ["Air India Regional", "", "India", "CD"],
    ["MDLR Airlines", "", "India", "9H"],
    ["Maldivian", "", "Maldives", "Q2"],
    ["Xpressair", "", "Indonesia", "XN"],
    ["Strategic Airlines", "", "Australia", "VC"],
    ["Al-Naser Airlines", "", "Iraq", "NA"],
    ["Fuji Dream Airlines", "", "Japan", "JH"],
    ["SGA Airlines", "", "Thailand", "5E"],
    ["Air2there", "", "New Zealand", "F8"],
    ["Avianova (Russia)", "", "Russia", "AO"],
    ["Parmiss Airlines (IPV)", "", "Iran", "PA"],
    ["EuropeSky", "", "Germany", "ES"],
    ["BRAZIL AIR", "BRAZIL AIR", "Brazil", "GB"],
    ["Homer Air", "Homer Sky", "Germany", "MR"],
    ["Court Line", "", "United Kingdom", "??"],
    ["South West Africa Territory Force", "SWATF", "Namibia", "??"],
    ["Lombards Air", "", "South Africa", "++"],
    ["U.S. Air", "", "United States", "-+"],
    ["Flitestar", "", "South Africa", "GM"],
    ["Llloyd Helicopters", "", "Australia", "::"],
    ["Wilderness Air", "", "Australia", ";;"],
    ["Whitaker Air", "", "Australia", "^^"],
    ["PanAm World Airways", "", "United States", "WQ"],
    ["Virginwings", "", "Germany", "YY"],
    ["KSY", "Kreta Sky", "Greece", "KY"],
    ["Buquebus Líneas Aéreas", "", "Uruguay", "BQ"],
    ["SOCHI AIR", "SOCHI", "Russia", "CQ"],
    ["Wizz Air Ukraine", "", "Ukraine", "WU"],
    ["88", "", "Cyprus", "47"],
    ["LCM AIRLINES", "", "Russia", "LQ"],
    ["Aero Brazil", "", "Brazil", "BZ"],
    ["Cambodia Angkor Air (K6)", "", "Cambodia", "K6"],
    ["Skyline nepc", "", "India", "D5"],
    ["THREE", "", "China", "H3"],
    ["Royal European Airlines", "", "United Kingdom", "69"],
    ["Tom's & co airliners", "Tom's air", "France", "&T"],
    ["Azul", "Azul Linhas Aéreas Brasileiras", "Brazil", "AD"],
    ["LSM Airlines", "slowbird", "Russia", "PQ"],
    ["LionXpress", "lionXpress", "Cameroon", "C4"],
    ["Nik Airways", "", "Saudi Arabia", "X1"],
    ["Genesis", "", "Pakistan", "GK"],
    ["Congo Express", "", "Congo (Kinshasa)", "XZ"],
    ["Fly Dubai", "", "United Arab Emirates", "FZ"],
    ["Domenican Airlines", "Domenican", "Dominican Republic", "D1"],
    ["Air Atlantic", "", "Canada", "9A"],
    ["Air Ops", "", "Sweden", "CR"],
    ["Aereonautica militare", "", "Italy", "JY"],
    ["LSM AIRLINES", "Russian. Yours Air Lines", "Russia", "YZ"],
    ["Aero Lloyd (YP)", "", "Germany", "YP"],
    ["UTair-Express", "", "Russia", "UR"],
    ["Huaxia", "HUAXIA", "China", "G5"],
    ["Zabaykalskii Airlines", "Baikal Airlines", "Russia", "ZP"],
    ["Marysya Airlines", "MARYSYA AIRLINES", "Russia", "M4"],
    ["N1", "", "Peru", "N1"],
    ["Airlink (SAA)", "", "South Africa", "4Z"],
    ["JobAir", "", "Czech Republic", "3B"],
    ["Zuliana de Aviacion", "Zuliana", "Venezuela", "OD"],
    ["Black Stallion Airways", "", "United States", "BZ"],
    ["German International Air Lines", "Germanair", "Germany", "GM"],
    ["TrasBrasil", "", "Brazil", "TB"],
    ["TransBrasil Airlines", "", "Brazil", "TH"],
    ["China SSS", "Chunqiu Airlines", "China", "9C"],
    ["Nihon.jet", "", "Japan", "NJ"],
    ["Transportes Aéreos Nacionales de Selva", "", "Peru", "TJ"],
    ["Air Mekong", "", "Vietnam", "P8"],
    ["Harbour Air (Priv)", "", "Canada", "H3"],
    ["Air Hamburg (AHO)", "", "Germany", "HH"],
    ["ZABAIKAL AIRLINES", "ZABAIKAL", "Russia", "Z6"],
    ["TransHolding", "Trans", "Brazil", "TI"],
    ["Yeti Airways", "", "Nepal", "YT"],
    ["Yellowstone Club Private Shuttle", "", "United States", "Y1"],
    ["Caucasus Airlines", "", "Georgia", "NS"],
    ["Serbian Airlines", "", "Serbia", "S1"],
    ["Windward Islands Airways", "", "Netherlands Antilles", "WM"],
    ["TransHolding System", "", "Brazil", "YO"],
    ["CCML Airlines", "", "Colombia", "CB"],
    ["Air Charter International", "", "France", "SF"],
    ["Fly Brasil", "Fly Brasil", "Brazil", "F1"],
    ["CB Airways UK ( Interliging Flights )", "", "United Kingdom", "1F"],
    ["Fly Colombia ( Interliging Flights )", "", "Colombia", "3F"],
    ["Trans Pas Air", "", "United States", "T6"],
    ["KMV", "", "Russia", "МИ"],
    ["Himalayan Airlines", "Himalaya", "Nepal", "HC"],
    ["Indya Airline Group", "Indya1", "India", "G1"],
    ["Sunwing", "", "Canada", "WG"],
    ["Japan Regio", "", "Japan", "ZX"],
    ["Norte Lineas Aereas", "NORTE", "Argentina", "N0"],
    ["Austral Brasil", "Austral Brasil lineas aereas", "Brazil", "W7"],
    ["PEGASUS AIRLINES-", "", "Turkey", "H9"],
    ["AirLiberté", "", "France", "IJ"],
    ["Camair-co", "", "Cameroon", "QC"],
    ["Aerocontinente (Priv)", "", "Peru", "N6"],
    ["Sky Regional", "Air Canada Express", "Canada", "RS"],
    ["TUR Avrupa Hava YollarÄ±", "TUR European Airways", "Turkey", "YI"],
    ["LSM International", "Moskva-air", "Russia", "II"],
    ["Baikotovitchestrian Airlines", "", "American Samoa", "BU"],
    ["Luchsh Airlines", "Air luch", "Russia", "L4"],
    ["Zimbabwean Airlines", "", "Zimbabwe", "Z7"],
    ["Air Cargo Germany", "", "Germany", "6U"],
    ["Mongolian International Air Lines", "Mongol Air", "Mongolia", "7M"],
    ["Alaniya Airlines", "Алания", "Russia", "2D"],
    ["Tway Airlines", "", "South Korea", "TW"],
    ["Papillon Grand Canyon Helicopters", "", "United States", "HI"],
    ["Jusur airways", "", "Egypt", "JX"],
    ["NEXT Brasil", "NEXT", "Brazil", "XB"],
    ["AeroWorld", "Sovet Air", "Russia", "W4"],
    ["Cook Island Air", "", "Cook Islands", "KH"],
    ["US Africa Airways", "", "United States", "E8"],
    ["GNB Linhas Aereas", "", "Brazil", "GN"],
    ["Usa Sky Cargo", "USky", "United States", "E1"],
    ["Hankook Airline", "", "South Korea", "HN"],
    ["Red Jet America", "", "United States", "RR"],
    ["REDjet", "", "Barbados", "Z7"],
    ["Hellenic Airways", "", "Greece", "1H"],
    ["Red Jet Andes", "", "Peru", "PT"],
    ["Red Jet Canada", "", "Canada", "QY"],
    ["Red Jet Mexico", "", "Mexico", "4X"],
    ["Marusya Airways", "Marusya Air", "Russia", "Y8"],
    ["Era Alaska", "", "United States", "7H"],
    ["AirRussia", "RussianConector", "Russia", "R8"],
    ["Hankook Air US", "", "United States", "H1"],
    ["NEPC Airlines", "", "India", "D5"],
    ["Canadian World", "", "Canada", "10"],
    ["I-Fly", "", "Russia", "H5"],
    ["T.A.T", "", "France", "IJ"],
    ["Alinord", "", "Italy", "DN"],
    ["Pacific Express", "", "United States", "VB"],
    ["VickJet", "", "France", "KT"],
    ["BVI Airways", "", "British Virgin Islands", "XV"],
    ["Salsa d'Haiti", "", "Haiti", "SO"],
    ["Zambezi Airlines (ZMA)", "", "Zambia", "ZJ"],
    ["Polet Airlines (Priv)", "", "Russia", "YQ"],
    ["TROPICAL LINHAS AEREAS", "TROPICAL", "Brazil", "T1"],
    ["12 North", "", "India", "12"],
    ["Mauritania Airlines International", "", "Mauritania", "L6"],
    ["MAT Airways", "", "Macedonia", "6F"],
    ["Asian Wings Airways", "", "Burma", "AW"],
    ["Air Arabia Egypt", "", "Egypt", "E5"],
    ["Alitalia Cityliner", "", "Italy", "CT"],
    ["Orchid Airlines", "", "Australia", "OI"],
    ["Asia Wings", "", "Kazakhstan", "Y5"],
    ["Skywest Australia", "", "Australia", "XR"],
    ["Nile Air", "", "Egypt", "NP"],
    ["Senegal Airlines", "", "Senegal", "DN"],
    ["Fly 6ix", "", "Sierra Leone", "6I"],
    ["Starbow Airlines", "", "Ghana", "S9"],
    ["Copenhagen Express", "", "Denmark", "0X"],
    ["BusinessAir", "", "Thailand", "8B"],
    ["SENIC AIRLINES", "", "United States", "YR"],
    ["Sky Wing Pacific", "", "South Korea", "C7"],
    ["Air Indus", "Indus Airlines Pak", "Pakistan", "PP"],
    ["Samurai Airlines", "Samurai Airlines (DUMMY)", "Pakistan", "07"],
    ["AirOne Continental", "AirOne Continental", "Slovakia", "00"],
    ["AirOne Polska", "AirOne Polska", "Poland", "U1"],
    ["Peach Aviation", "", "Japan", "MM"],
    ["Aviabus", "", "Russia", "U1"],
    ["Michael Airlines", "Javi", "Puerto Rico", "DF"],
    ["Korongo Airlines", "", "Congo (Kinshasa)", "ZC"],
    ["Indonesia Sky", "", "Indonesia", "I5"],
    ["Pelangi", "", "Malaysia", "9P"],
    ["Aws express", "", "United States", "B0"],
    ["Southjet", "", "United States", "76"],
    ["Southjet connect", "", "United States", "77"],
    ["Air Cape", "", "South Africa", "KP"],
    ["Southjet cargo", "", "United States", "78"],
    ["Iberia Express", "", "Spain", "I2"],
    ["Interjet (ABC Aerolineas)", "", "Mexico", "4O"],
    ["AirOnix", "", "Ukraine", "OG"],
    ["Nordic Global Airlines", "", "Finland", "NJ"],
    ["Scoot", "", "Singapore", "TZ"],
    ["Starling Airlines Spain", "", "Spain", "SX"],
    ["Hi Fly (5K)", "", "Portugal", "5K"],
    ["China Northwest Airlines (WH)", "", "China", "WH"],
    ["Zenith International Airline", "Zenith", "Thailand", "ZN"],
    ["Orbit Airlines Azerbaijan", "Orbit Azerbaijan", "Azerbaijan", "O1"],
    ["Air Alps Aviation (A6)", "", "Austria", "A6"],
    ["Patriot Airways", "", "United States", "P4"],
    ["Vision Airlines (V2)", "", "United States", "V2"],
    ["Chicago Express (C8)", "ATA Connection", "United States", "C8"],
    ["BQB Lineas Aereas", "Buquebus", "Uruguay", "5Q"],
    ["Yellowtail", "", "United States", "YE"],
    ["Royal Airways", "Royal Inc.", "United States", "KG"],
    ["FlyHigh Airlines Ireland (FH)", "", "Ireland", "FH"],
    ["Aero VIP (2D)", "", "Portugal", "2D"],
    ["Yangon Airways Ltd.", "", "Burma", "YH"],
    ["T.J. Air", "", "United States", "TJ"],
    ["SkyWork Airlines", "", "Switzerland", "SX"],
    ["ValueJet", "", "United States", "J7"],
    ["Maastricht Airlines", "", "Netherlands", "W2"],
    ["CheapFlyingInternational", "CheapFlying", "France", "WL"],
    ["Aviaexpresscruise", "", "Russia", "E6"],
    ["Euro Jet", "", "Germany", "24"],
    ["AirOne Atlantic", "AirOneAtlantic", "Slovakia", "00"],
    ["HQ- Business Express", "", "United States", "HQ"],
    ["Royal Southern Airlines.", "Royal Southern", "Colombia", "R1"],
    ["SOCHI AIR CHATER", "Sochi Air", "Russia", "Q3"],
    ["Denim Air", "FlyNonstop", "Norway", "J7"],
    ["WestAir", "", "United States", "OE"],
    ["WestAir Airlines", "", "United States", "OE"],
    ["WestAir Airlines", "", "United States", "OE"],
    ["North Pacific Airlines", "", "United States", "NO"],
    ["Malindo Air", "", "Malaysia", "OD"],
    ["Tramm Airlines", "Tramm Airlines", "Netherlands Antilles", "9F"],
    ["Lina Congo", "", "Congo (Brazzaville)", "GC"],
    ["Flightlink Tanzania", "Flightlink", "Tanzania", "Z9"],
    ["IzAvia", "", "Russia", "I8"],
    ["3 Valleys Airlines", "", "France", "3V"],
    ["Maryland Air", "Maryland", "United States", "M1"],
    ["Insel Air (7I/INC) (Priv)", "", "Netherlands Antilles", "7I"],
    ["VivaColombia", "", "Colombia", "5Z"],
    ["Apache Air", "Apache", "United States", "ZM"],
    ["MHS Aviation GmbH", "", "Germany", "M2"],
    ["Jettor Airlines", "Jettor", "Hong Kong", "NR"],
    ["GoDutch", "", "Netherlands", "GD"],
    ["Thai Lion Air", "", "Thailand", "SL"],
    ["Deutsche Luftverkehrsgesellschaft", "", "Germany", "DW"],
    ["National Air Cargo", "", "United States", "N8"],
    ["Eastern Atlantic Virtual Airlines", "", "United States", "13"],
    ["Citilink Indonesia", "", "Indonesia", "QG"],
    ["Gulisano airways", "", "Italy", "GU"],
    ["Caribbean Wings", "", "Turks and Caicos Islands", "XP"],
    ["Snowbird Airlines", "", "Finland", "S8"],
    ["Kharkiv Airlines", "", "Ukraine", "KH"],
    ["XAIR USA", "", "United States", "XA"],
    ["Air Costa", "", "India", "LB"],
    ["Global Freightways", "", "United States", "F5"],
    ["XPTO", "XPTO", "Portugal", "XP"],
    ["Malawian Airlines", "", "Malawi", "3W"],
    ["Avilu", "Avilu' SA", "Switzerland", ".."],
    ["Air Serbia", "", "Serbia", "JU"],
    ["Air Lituanica", "Air Lituanica", "Lithuania", "LT"],
    ["Rainbow Air (RAI)", "Rainbow Air (RAI)", "United States", "RN"],
    ["Rainbow Air Canada", "Rainbow Air CAN", "Canada", "RY"],
    ["Rainbow Air Polynesia", "Rainbow Air POL", "United States", "RX"],
    ["Rainbow Air Euro", "Rainbow Air EU", "United Kingdom", "RU"],
    ["Rainbow Air US", "Rainbow Air US", "United States", "RM"],
    ["Dobrolet", "Добролёт", "Russia", "QD"],
    ["Spike Airlines", "Aero Spike", "United States", "S0"],
    ["All Argentina", "All Argentina", "Argentina", "L1"],
    ["All America", "All America", "United States", "A2"],
    ["All Asia", "All Asia", "China", "L9"],
    ["All Africa", "All Africa", "South Africa", "9A"],
    ["Regionalia México", "Regionalia México", "Mexico", "N4"],
    ["All Europe", "All Europe", "United Kingdom", "N9"],
    ["All Spain", "All Spain", "Spain", "N7"],
    ["Regional Air Iceland", "Regional Air Iceland", "Iceland", "9N"],
    ["British Air Ferries", "", "United Kingdom", "??"],
    ["Voestar", "Voestar Brasil", "Brazil", "8K"],
    ["All Colombia", "All Colombia", "Colombia", "7O"],
    ["Regionalia Uruguay", "Regionalia Uruguay", "Uruguay", "2X"],
    ["Regionalia Venezuela", "Regionalia Venezuela", "Venezuela", "9X"],
    ["Regionalia Chile", "Regionalia Chile", "Chile", "9J"],
    ["Vuela Cuba", "Vuela Cuba", "Cuba", "6C"],
    ["All Australia", "All Australia", "Australia", "88"],
    ["Fly Europa", "", "Spain", "ER"],
    ["FlyPortugal", "", "Portugal", "PO"],
    ["Spring Airlines Japan", "", "Japan", "IJ"],
    ["Dense Airways", "", "United States", "KP"],
    ["Dense Connection", "", "United States", "KZ"],
    ["Vuola Italia", "Vuola Italia", "Italy", "4S"],
    ["Island Express Air", "", "Canada", "1X"],
    ["All Argentina Express", "All Argentina Express", "Argentina", "Z0"],
    ["Thai Smile Airways", "THAI Smile", "Thailand", "WE"],
    ["International AirLink", "", "Jamaica", "I4"],
    ["Real Tonga", "", "Tonga", "RT"],
    ["All America AR", "All America Argentina", "Argentina", "2R"],
    ["All America CL", "All America Chile", "Chile", "1R"],
    ["SOCHI AIR EXPRESS", "ADLER EXPRESS", "Russia", "Q4"],
    ["All America BR", "All America Brasil", "Brazil", "1Y"],
    ["FRA Air", "", "Germany", "X9"],
    ["Royal", "", "Canada", "QN"],
    ["GREAT LAKES (GX)", "", "Canada", "GX"],
    ["Volotea Costa Rica", "Volotea Costa Rica", "Costa Rica", "9V"],
    ["Fly Romania", "", "Romania", "X5"],
    ["Eagle Atlantic Airlines", "", "Ghana", "E2"],
    ["All America CO", "All America Colombia", "Colombia", "0Y"],
    ["All America MX", "All America México", "Mexico", "0M"],
    ["FOX Linhas Aereas", "", "Brazil", "FX"],
    ["Wings of England", "", "United Kingdom", "EX"],
    ["Air Kenya (Priv)", "", "Kenya", "QP"],
    ["Via Conectia Airlines", "Via Conectia", "Uruguay", "6V"],
    ["City Airways", "", "Thailand", "E8"],
    ["Norwegian Long Haul AS", "", "Norway", "DU"],
    ["TransNusa Air", "", "Indonesia", "M8"],
    ["Tomp Airlines", "Tomp Airlines", "Chile", "ZT"],
    ["OneJet", "", "United States", "J1"],
    ["Global Airlines", "Global Airlines", "Argentina", "0G"],
    ["International Flying Service", "IFS", "Italy", "F4"],
    ["Air Vistara", "Tata SIA Airlines", "India", "UK"],
    ["TransRussiaAirlines", "TransRus", "Russia", "1E"],
    ["Severstal Air Company", "", "Russia", "D2"],
    ["REXAIR VIRTUEL", "", "France", "RR"],
    ["WestJet Encore", "Encore", "Canada", "WR"],
    ["Air Pegasus", "", "India", "OP"],
    ["International Europe", "International", "Spain", "9I"],
    ["V Air", "V Air Taiwan", "Taiwan", "ZV"],
    ["Naka Nihon Airlines Service", "", "Japan", "NV"],
    ["Islands Express", "", "United States", "X9"],
    ["Atlantic Air Services", "", "United States", "X7"],
    ["Boutique Air (Priv)", "", "United States", "4B"],
    ["VOLOTEA Airways", "", "Spain", "V7"],
    ["Aguilar Connect", "", "Chile", "3X"],
    ["ROYAL BRITAIN", "Flying Brits", "United Kingdom", "7V"],
    ["INAVIA Internacional", "Internacional", "Argentina", "Z5"],
    ["Liberty Airways", "", "United States", "LE"],
    ["Аэросервис", "", "Russia", "АЯ"],
    ["Bassaka airlines", "", "Cambodia", "5B"],
    ["SkyBahamas Airlines", "", "Bahamas", "Q7"],
    ["UVT Aero", "", "Russia", "UW"],
    ["Silver Airways (3M)", "", "United States", "3M"],
    ["ATA Airlines (Iran)", "هواپیمایی آتا", "Iran", "I3"],
    ["VIA Líneas Aéreas", "VIA", "Argentina", "V1"],
    ["Palair Macedonia", "", "Macedonia", "3D"],
    ["Palair Macedonia (3D)", "", "Macedonia", "3D"],
    ["GermanXL", "", "Germany", "GX"],
    ["Fly France", "Fly France", "France", "FF"],
    ["Europe Jet", "Europe Jet", "France", "EX"],
    ["Deutsche Luftverkehrsgesellschaft (DLT)", "", "Germany", "DW"],
    ["Atlantic Air Cargo", "", "United States", "K3"],
    ["World Scale Airlines", "World Scale", "United States", "W3"],
    ["All America US", "All America US", "United States", "AG"],
    ["BudgetAir", "BudgetAir", "Germany", "1K"],
    ["Fly One", "Fly One", "Moldova", "F5"],
    ["Nordica", "", "Estonia", "EE"],
    ["Dummy", "", "France", "0E"],
    ["All America BOPY", "All America BOPY", "Paraguay", "0P"],
    ["Air Andaman (2Y)", "", "Thailand", "2Y"],
    ["Jetgo Australia", "", "Australia", "JG"],
    ["Air Carnival", "", "India", "2S"],
    ["Svyaz Rossiya", "Russian Commuter", "Russia", "7R"],
]
