[project]
name = "sutherland"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "amadeus>=12.0.0",
    "faker>=37.0.2",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
]
